name: Create File Structure

on: 
  issues:
    types: opened

jobs:

  create-structure:
    if: github.event.issue.labels[1] != null && (contains(github.event.issue.labels.*.name, 'initiation')) && contains(join(github.event.issue.labels.*.name, ' '), 'priority')
    runs-on: ubuntu-latest
    env: 
          BRANCH_NAME: ${{needs.create-and-checkout-branch.outputs.branch_name}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          URL: ${{ github.event.issue.url }}
          ISSUE_BODY: ${{ github.event.issue.body }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set branch name
        id: set-branch-name
        run: |
          # Generate a dynamic branch name based on the current date and time
          branch_name="branch-$NUMBER"
          echo "branch_name=$branch_name" >> "$GITHUB_OUTPUT"
          
      - name: Create branch
        run: |
          branch_name="${{ steps.set-branch-name.outputs.branch_name }}"
          git checkout -b $branch_name
          git push --set-upstream origin $branch_name
          
      - name: Switch to the new branch
        run: |
          git fetch
          git switch ${{ steps.set-branch-name.outputs.branch_name }}

      - name: Install dependencies
        run: |
          chmod +x .sidmd/install_dependencies.sh
          .sidmd/install_dependencies.sh 
          
      - name: Run AI query
        run: |
          output=$(python .sidmd/generate_code.py 'initiation' "$ISSUE_BODY" '')
          echo "$output"
          echo "$output" | bash
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated creation of file structure"
          git push

      - name: Handle failure
        if: failure()
        run: |
          BODY="The workflow could not be completed, changes from the comment have not been implemented. Please try again. To find out more about the error, see workflow run at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          gh issue comment "$NUMBER" --body "$BODY"

      - name: Post a comment
        if: success()
        run: |
          BODY="The code has been successfully generated. Please review the changes in the latest commit of branch  ${{ github.server_url }}/${{ github.repository }}/tree/${{ steps.set-branch-name.outputs.branch_name }}"
          gh issue comment "$NUMBER" --body "$BODY"

      - name: Create a pull request to review changes
        run: gh pr create -B main -H ${{ steps.set-branch-name.outputs.branch_name }} --title 'Merge ${{ steps.set-branch-name.outputs.branch_name }} into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        
